export const LOCKDOWN_POLICIES = [0, 1, 2, 3];
export const MASK_POLICIES = [0, 1, 2, 3, 4];
export const VACCINE_POLICIES = [0, 1, 2, 3, 4, 5];
export const VACCINATED_POPULATION = [
  {
    level: "High",
    value: 3,
  },
  {
    level: "Medium",
    value: 2,
  },
  {
    level: "Low",
    value: 1,
  },
];
export const CITIES = [
  "Adenau",
  "Andernach",
  "Annweiler am Trifels",
  "Bacharach",
  "Bad Bergzabern",
  "Bad Breisig",
  "Bad Dürkheim",
  "Bad Ems",
  "Bad Hönningen",
  "Bad Kreuznach",
  "Bad Marienberg",
  "Bad Neuenahr-Ahrweiler",
  "Bad Sobernheim",
  "Baumholder",
  "Bellheim",
  "Bendorf",
  "Bernkastel-Kues",
  "Betzdorf",
  "Bingen am Rhein",
  "Bitburg",
  "Bobenheim-Roxheim",
  "Boppard",
  "Braubach",
  "Burgbrohl",
  "Cochem",
  "Daaden",
  "Dahn",
  "Deidesheim",
  "Diez",
  "Dierdorf",
  "Edenkoben",
  "Eisenberg (Pfalz)",
  "Enkenbach-Alsenborn",
  "Emmelshausen",
  "Frankenthal (Pfalz)",
  "Freinsheim",
  "Gau-Algesheim",
  "Germersheim",
  "Gerolstein",
  "Grünstadt",
  "Guntersblum",
  "Hachenburg",
  "Hagenbach",
  "Herdorf",
  "Hermeskeil",
  "Hillesheim",
  "Herxheim bei Landau/Pfalz",
  "Höhr-Grenzhausen",
  "Hornbach",
  "Idar-Oberstein",
  "Ingelheim am Rhein",
  "Kaisersesch",
  "Kaiserslautern",
  "Kandel",
  "Kastellaun",
  "Katzenelnbogen",
  "Kaub",
  "Kirchberg (Hunsrück)",
  "Kirchen (Sieg)",
  "Kirchheimbolanden",
  "Kirn",
  "Koblenz",
  "Konz",
  "Kyllburg",
  "Lahnstein",
  "Lambrecht (Pfalz)",
  "Landau in der Pfalz",
  "Landstuhl",
  "Lauterecken",
  "Linz am Rhein",
  "Ludwigshafen am Rhein",
  "Mainz",
  "Manderscheid",
  "Mendig",
  "Monsheim",
  "Montabaur",
  "Mutterstadt",
  "Neustadt an der Weinstraße",
  "Nieder-Olm",
  "Nierstein",
  "Ober-Olm",
  "Osthofen",
  "Pirmasens",
  "Ramstein-Miesenbach",
  "Ransbach-Baumbach",
  "Remagen",
  "Rheinböllen",
  "Rheinbreitbach",
  "Rülzheim",
  "Sankt Goar",
  "Sankt Goarshausen",
  "Simmern/Hunsrück",
  "Sinzig",
  "Speyer",
  "Sprendlingen",
  "Stadecken-Elsheim",
  "Trier",
  "Vallendar",
  "Wachenheim an der Weinstraße",
  "Waldalgesheim",
  "Waldmohr",
  "Wörms",
  "Wörrstadt",
  "Zell (Mosel)",
  "Zweibrücken",
];
